server:
  port: 8088
web:
  video-path: D:/soft/upload
#spring druid 连接池

spring:
  application:
    name: nvss-actuator
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.212.32:8848

  datasource:
    #10.10.24.142

    url: jdbc:mysql://101.200.220.47:3306/nvs3000?useUnicode=true&amp;characterEncoding=UTF-8&autoReconnect=true
    #    url: jdbc:mysql://101.200.123.93:3306/nvs3000?useUnicode=true&amp;characterEncoding=UTF-8&autoReconnect=true
    username: root
    #    password: 6000
    password: 1qA2wS3De
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/test/,classpath:/templates/,file:${web.video-path}
  redis:
    #测试
    host: 101.200.123.93
    #生产
    #    host: 39.106.141.171
    database: 0
    port: 6379
    timeout: 3000ms
    #=========redis线程池设置=========
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 200
        #连接池中的最小空闲连接，默认值也是0。
        min-idle: 200
        max-active: 200
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时
        max-wait: 1000ms
  freemarker:
    cache: false
    charset: UTF-8
    allow-request-override: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
##################
#  MQTT 配置
##################
# 用户名
mqtt:
  username: admin
  # 密码
  password: public
  # 推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
  url : tcp://101.200.221.78:32627
  ##################
  #  MQTT 生产者
  ##################
  # 连接服务器默认客户端ID
  producer:
   clientId: mqttProducer
  # 默认的推送主题，实际可在调用接口时指定
   defaultTopic: webmu/serversinfo
  ##################
  #  MQTT 消费者
  ##################
  # 连接服务器默认客户端ID
  consumer:
   clientId: mqttConsumer
  # 默认的接收主题，可以订阅多个Topic，逗号分隔
   defaultTopic: webmu/serversinfo