


#spring druid¡¨Ω”≥ÿ
spring:
  datasource:
    url: jdbc:mysql://101.200.123.93:3306/nvs3000?useUnicode=true&amp;characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 6000
    type: com.alibaba.druid.pool.DruidDataSource