
server:
  port: 8090
web:
  video-path: D:/soft/upload
#spring druid 连接池
spring:
  datasource:
    url: jdbc:mysql://101.200.123.93:3306/nvs3000?useUnicode=true&amp;characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 6000
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/test/,classpath:/templates/,file:${web.video-path}
  freemarker:
    cache: false
    charset: UTF-8
    allow-request-override: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html